/**
 * Centralized Site Content & Customization Configuration
 * Auto-generated by Client Project Factory Visual CMS
 */
export const siteConfig = {
  "name": "dodo",
  "company": "dodo",
  "branding": {
    "primaryColor": "#49f40b",
    "secondaryColor": "#ea101b",
    "accentColor": "#38bdf8",
    "font": "Inter",
    "tagline": "hi",
    "metaTitle": "dodo | dodo",
    "metaDescription": "Production Deployment\nDeployment\napp-4jji6mpby-workeg.vercel.app\nDomains\napp-web-psi-ashen.vercel.app\nStatus\nReady\nCreated\n18m ago by analolo6000-2808\n\nanalolo6000-2808 Avatar\nSource\nmain\n3fcabe6\nfix: escape metadata title and description with JSON.stringify in all …\n\nDeployment Settings\n3 Recommendations\nTo deploy to Production, drop your project anywhere on this page, connect to git, or run vercel --prod via the CLI.\nProduction Checklist\n\n0/5\nConnect Git Repository\nAdd Custom Domain\nPreview Deployment\nEnable Web Analytics\nEnable Speed Insights\nObservability\n\n6h\nEdge Requests\n162\n"
  },
  "hero": {
    "headline": "Welcome to dodo",
    "tagline": "hi",
    "ctaText": "Get Started",
    "ctaUrl": "#contact",
    "heroImageUrl": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80"
  },
  "products": [
    {
      "id": "prod-1",
      "title": "Premium Pro Service / Product",
      "price": "$99.00",
      "category": "Featured",
      "imageUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
      "description": "High-performance enterprise solution with dedicated 24/7 priority support.",
      "inStock": true
    },
    {
      "id": "prod-1787573487712",
      "title": "New Service / Product",
      "price": "$49.00",
      "category": "Featured",
      "imageUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
      "description": "High quality solution designed to elevate your business performance.",
      "inStock": true
    },
    {
      "id": "prod-1787573489662",
      "title": "New Service / Product",
      "price": "$49.00",
      "category": "Featured",
      "imageUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
      "description": "High quality solution designed to elevate your business performance.",
      "inStock": true
    }
  ],
  "pricing": [
    {
      "id": "tier-starter",
      "name": "Starter",
      "price": "$29/mo",
      "period": "Monthly",
      "popular": false,
      "features": [
        "Core Features Access",
        "Up to 5 Team Members",
        "Community Support",
        "Basic Analytics"
      ],
      "ctaText": "Choose Starter"
    },
    {
      "id": "tier-pro",
      "name": "Professional",
      "price": "$79/mo",
      "period": "Monthly",
      "popular": true,
      "features": [
        "Everything in Starter",
        "Unlimited Team Members",
        "24/7 Priority Support",
        "Advanced Customizations",
        "Custom Domain"
      ],
      "ctaText": "Get Professional"
    },
    {
      "id": "tier-1787573501912",
      "name": "Custom Package",
      "price": "$49/mo",
      "period": "Monthly",
      "popular": false,
      "features": [
        "Essential Access",
        "Dedicated Support",
        "Cloud Storage"
      ],
      "ctaText": "Choose Package"
    }
  ],
  "contact": {
    "email": "alyseteen60@gmail.com",
    "phone": "01093706027",
    "whatsapp": "01142466903",
    "address": "hfhjefghe987347764hjegd738"
  }
};
